project_id = "rdsudzwcdtawnrhhbecv"

[functions.prayer-times]
verify_jwt = true

[functions.weekly-summary]
verify_jwt = true

[functions.daily-quiz]
verify_jwt = false

[functions.generate-learn-content]
verify_jwt = false

[functions.generate-dua]
verify_jwt = false
